<a href="https://colab.research.google.com/github/mohammadabdulraouf786/dataanalysis_withpython/blob/main/DA_DAY2_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Randam module is sub-pacakge of numpy

In [ ]:
a=np.arange(32).reshape(8,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
a=np.random.rand(1)
print(a)

[0.87696973]


In [ ]:
a=np.random.rand(8,4)#rand range is 0-1
print(a)

[[0.57464117 0.83687068 0.45425328 0.60496999]
 [0.72568792 0.46054256 0.71147165 0.40739646]
 [0.33595454 0.4068873  0.00841026 0.33083781]
 [0.38059563 0.57535552 0.6699255  0.31599232]
 [0.98600216 0.66111631 0.29085235 0.89510749]
 [0.46764918 0.93424498 0.48867401 0.17995965]
 [0.63598249 0.57167986 0.20013252 0.26317498]
 [0.4270372  0.02630446 0.45361937 0.28286854]]


In [ ]:
a=10*np.random.rand(8,4)
print(a)

[[6.3815958  7.98207843 1.94746589 2.963545  ]
 [0.58624162 8.51492045 5.30809315 2.82846371]
 [6.22739918 4.24276193 9.35374635 0.94670103]
 [9.17174569 0.166081   4.77829622 5.15957417]
 [2.4274675  8.581914   1.90223209 3.49360303]
 [4.62230184 3.64042418 8.79588321 3.13228233]
 [5.86085476 8.70201802 8.66564686 6.62118116]
 [8.0875223  6.58909685 0.93450617 3.04334952]]


In [ ]:
a=np.floor(10*np.random.rand(8,4))
print(a)

[[0. 4. 6. 3.]
 [4. 0. 2. 1.]
 [6. 0. 9. 6.]
 [2. 8. 9. 2.]
 [5. 3. 4. 5.]
 [0. 7. 7. 5.]
 [8. 1. 1. 7.]
 [5. 9. 6. 4.]]


In [ ]:
print(np.vsplit(a,4))

[array([[0., 4., 6., 3.],
       [4., 0., 2., 1.]]), array([[6., 0., 9., 6.],
       [2., 8., 9., 2.]]), array([[5., 3., 4., 5.],
       [0., 7., 7., 5.]]), array([[8., 1., 1., 7.],
       [5., 9., 6., 4.]])]


In [ ]:
np.vsplit(a,4)

[array([[0., 4., 6., 3.],
        [4., 0., 2., 1.]]),
 array([[6., 0., 9., 6.],
        [2., 8., 9., 2.]]),
 array([[5., 3., 4., 5.],
        [0., 7., 7., 5.]]),
 array([[8., 1., 1., 7.],
        [5., 9., 6., 4.]])]

In [ ]:
np.vsplit(a,(3,5))#split after 3 row and 5 row

[array([[0., 4., 6., 3.],
        [4., 0., 2., 1.],
        [6., 0., 9., 6.]]),
 array([[2., 8., 9., 2.],
        [5., 3., 4., 5.]]),
 array([[0., 7., 7., 5.],
        [8., 1., 1., 7.],
        [5., 9., 6., 4.]])]

In [ ]:
#create an array with 4 rows and 8 columns
a=np.arange(32).reshape(4,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [ ]:
np.vsplit(a,4)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31]])]

In [ ]:
np.hsplit(a,4)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [ ]:
np.hsplit(a,(3,7))

[array([[ 0,  1,  2],
        [ 8,  9, 10],
        [16, 17, 18],
        [24, 25, 26]]),
 array([[ 3,  4,  5,  6],
        [11, 12, 13, 14],
        [19, 20, 21, 22],
        [27, 28, 29, 30]]),
 array([[ 7],
        [15],
        [23],
        [31]])]

In [ ]:
np.hsplit(a,(2,5))

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3,  4],
        [10, 11, 12],
        [18, 19, 20],
        [26, 27, 28]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31]])]

Trigonmetry

In [ ]:
np.pi

3.141592653589793

In [ ]:
a=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(a)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(a)#convert radians to degree

array([ 45.,  60.,  90., 180.])

In [ ]:
np.deg2rad(a)#convert degree to radians

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [ ]:
np.sin(0.785)#radians

0.706825181105366

In [ ]:
np.sin(1)#radians

0.8414709848078965

In [ ]:
np.tan(1)#radians

1.5574077246549023

In [ ]:
np.cos(1)#radians

0.5403023058681398

statistics

In [ ]:
a=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(a)#average value

46.5

In [ ]:
np.median(a)#middle value

39.5

In [ ]:
np.var(a)#variance value

597.9166666666666

In [ ]:
np.std(a)#standard deviation

24.452334585202017

In [ ]:
a=np.arange(1,5).reshape(2,2)
print(a)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
a=np.arange(1,25).reshape(6,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
a=np.arange(1,25).reshape(6,4)
print(np.argmax(a))

23


In [ ]:
a=np.floor(10*np.random.rand(24)).reshape(6,4)
print(a)

[[9. 6. 7. 6.]
 [1. 8. 1. 4.]
 [4. 9. 6. 3.]
 [7. 9. 5. 6.]
 [0. 7. 9. 7.]
 [0. 4. 4. 8.]]


In [ ]:
print(np.argmax(a))

0


In [ ]:
a=10*np.random.rand(24).reshape(6,4)
print(a)

[[2.48892259 1.90205182 5.67578972 0.62909418]
 [9.77331565 7.91400694 5.96542492 1.65470247]
 [7.80709722 9.93641993 2.23788703 3.03516988]
 [0.29871216 1.87542791 0.94556903 0.66906544]
 [0.12736899 2.69224847 3.69662471 5.46144578]
 [7.68864377 5.12457381 3.51861943 7.74662111]]


In [ ]:
print(np.argmax(a))

9


In [ ]:
print(np.argmax(a,axis=1))

[2 0 1 1 3 3]


In [ ]:
print(np.argmin(a))

16


In [ ]:
print(np.argmin(a,axis=1))

[3 3 2 0 0 2]


In [ ]:
print(np.argmin(a,axis=0))

[4 3 3 0]


In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))

(array([0, 1, 4]),)


In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==1))

(array([2, 3, 5]),)


In [ ]:
a=np.array([24,14,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [ ]:
a=np.array([6,7,8,9,10])#it is used to search and sorted the element
b=np.searchsorted(a,10)
print(b)

4


In [ ]:
a=np.array(['zoro','luffy','nami'])
print(np.sort(a))

['luffy' 'nami' 'zoro']


In [ ]:
a=np.array(['true','false','true'])
print(np.sort(a))

['false' 'true' 'true']


In [ ]:
a=np.array([[3,2,4],[5,0,1]])
print(np.sort(a)a=np.array([34,56,7,17,88,91])
print(np.where(a%2==1)))

[[2 3 4]
 [0 1 5]]


filtering

In [ ]:
a=np.array([34,56,7,17,88,91])
flit=np.where(a%2==0)
print(flit)

(array([0, 1, 4]),)


In [ ]:
a[flit]

array([34, 56, 88])

iterating through two arays

In [ ]:
a=np.array(['zoro','luffy','nami'])
b=np.array(['r','m','t'])
for i,j in zip(b,a):
  print(i,".",j)

r . zoro
m . luffy
t . nami


In [ ]:
a=np.array(['zoro','luffy','sanji'])
b=np.array(['nova','d','foot'])
c=np.array(['rono','monkey','black'])
for i,j,k in zip(c,b,a):
  print(i,".",j,".",k)

rono . nova . zoro
monkey . d . luffy
black . foot . sanji


In [ ]:
a=np.array([34,56,7,17,88,91])
b=np.array([24,14,7,17,54,60])
n=np.multiply(a,b)
print(n)

[ 816  784   49  289 4752 5460]


In [ ]:
a=np.array([34,56,7,17,88,91])
b=np.array([24,14,7,17,54,60])
n=np.divide(a,b)
print(n)

[1.41666667 4.         1.         1.         1.62962963 1.51666667]


In [ ]:
a=np.array([34,56,7,17,88,91])
b=np.array([24,14,7,17,54,60])
n=np.mod(a,b)
print(n)

[10  0  0  0 34 31]


In [ ]:
a=np.array([34,56,7,17,88,91])
b=np.array([24,14,7,17,54,60])
n=np.divmod(a,b)
print(n)

(array([1, 4, 1, 1, 1, 1]), array([10,  0,  0,  0, 34, 31]))


logarithims

In [ ]:
a=np.arange(1,10)
print(a)
print(np.log2(a))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
a=1.2
print(np.log(a))

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a))

0.2630344058337938


In [ ]:
a=1.2
print(np.log10(a))

0.07918124604762482


In [ ]:
a=np.array([1,2,3,4,5,6,7])
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015]


other mathematical function

In [ ]:
a=np.array([1,2,3,4,5,6,7])
b=np.cumprod(a)
print(b)

[   1    2    6   24  120  720 5040]


In [ ]:
a=np.array([1,2,3,4,5,6,7])
b=np.cumsum(a)
print(b)

[ 1  3  6 10 15 21 28]


In [ ]:
a=np.array([1,2,3,4,5,6,7])
b=np.diff(a)
print(b)

[1 1 1 1 1 1]


In [ ]:
n1=455
n2=665
a=np.lcm(n1,n2)
print(a)

8645


In [ ]:
n1=455
n2=665
a=np.gcd(n1,n2)
print(a)

35


In [ ]:
a=np.array([34,56,7])
b=np.gcd.reduce(a)#take multiple inputs gives single inputs
print(b)

1


In [ ]:
a=np.array([34,56,7])
b=np.lcm.reduce(a)#take multiple inputs gives single inputs
print(b)

952
